blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/ORG_NAME/REPO_NAME/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: https://github.com/ORG_NAME/REPO_NAME#readme
    about: Check out the documentation
